import './styles/global.css'
import './styles/header.css'
import './styles/form.css'
import './styles/main.css'
import './styles/loyaltyCard.css'
import './styles/userDetails.css'
import './styles/progressBar.css'
import './styles/history.css'

import './modules/actions.js'
import './modules/user.js'
import './modules/history.js'
import './modules/loyaltyCard.js'
import './modules/progressBar.js'